### ISSUE TITLE
Versioning DB

### ISSUE THREAD

**Issue by sudheerDev** [ocombe/angular-localForage#117]
What is the best way to manage DB versioning when using indexedDB
i keep getting this error in one browser or the other.

`DOMException: Version change transaction was aborted in upgradeneeded event handler.`

What is the primary reason for having version key as part of config. Can anyone please elaborate on this?

**Comment by scotttrinh** [comment]
Hey, @sudheerDev. I wish I was more knowledgeable about IndexedDB so I could offer some insight. Might be worth opening the question up with [localForage](https://github.com/mozilla/localForage), since this repo is mainly just a wrapper for that library.

Since this isn't an issue with the repo, I'm going to close this issue, but if you learn anything you think should be added to the docs, I'd definitely welcome a documentation PR that made it more clear what to do.

**Comment by scotttrinh** [comment]
BTW, feel free to re-open the issue if you find that there is something awry with our implementation in this area.

**Comment by sudheerDev** [comment]
@scotttrinh sure ya i will raise it in localForage. Will update documentation if I learn about it.
