### ISSUE TITLE
Q:  Is there the maximun about angular-localForage

### ISSUE THREAD

**Issue by yaoyiee** [ocombe/angular-localForage#127]
1. Is there the maximun about angular-localForage？

2.How to calculate the size of the data that has been stored？

**Comment by scotttrinh** [comment]
This repo is really just a wrapper around [localForage](https://github.com/localForage/localForage), so that is a better question for them. I can give you a clue that it depends on the client, since it uses different backends depending on the browser it's loaded in. 

Here is some light reading on the subject:

- https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria
- https://developers.google.com/web/updates/2011/11/Quota-Management-API-Fast-Facts

Since this isn't really an angular-localForage issue, I'm closing this issue, but feel free to reply if you have questions about how angular-localForage might effect your storage needs.
