### ISSUE TITLE
Using directive and deleting value keeps 3 characters in the field

### ISSUE THREAD

**Issue by Diego251** [ocombe/angular-localForage#132]
Hello, I'm using the directive version to store values in a form. It's working well, except that whenever I delete values, it always keeps at least 3 characters. Tried on Chrome and Explorer (ionic serve), but also on HTC M8 and iPhone SE. Is there something I am doing wrong?

**Comment by scotttrinh** [comment]
What do you mean by "delete values"? Also, what do you mean by "always keeps at least 3 characters"? 

Possible meanings of "delete values":
1. use the keyboard to delete or backspace characters in the input field you bound it to
2. remove the value from localForage
3. unbind the value

Possible meanings of "it always keeps a least 3 characters":
1. localForage contains the characters
2. input field contains the characters
3. ng-model contains the characters
4. `1 && 2`
5. `1 && 3`
6. `2 && 3`

Let me know, and I'm sure we can get you on the right path!

**Comment by Diego251** [comment]
Hello, thank you for your quick answer.

It seems that the issue is linked with the "ng-minlength" angular directive and/or also with the "required" attribute for form input fields. Removing ng-minlength or setting it to '0' does not help but then there is at least 1 value stored for the form field, even if the value is deleted by the user.

I ended up removing the directive and storing/loading the values like this (see below). If you see a better way please let me know... thanks!

```
  function loadForm() {
    var firstName;
    var lastName;
    var address;
    var zipCode;
    var city;
    var email;
    var phone;
    var country;

    Promise.all([
      $localForage.getItem('supportForm.FirstName').then(function(data) { firstName = data; }),
      $localForage.getItem('supportForm.LastName').then(function(data)  { lastName = data; }),
      $localForage.getItem('supportForm.Address').then(function(data)   { address = data; }),
      $localForage.getItem('supportForm.ZipCode').then(function(data)   { zipCode = data; }),
      $localForage.getItem('supportForm.City').then(function(data)      { city = data; }),
      $localForage.getItem('supportForm.Email').then(function(data)     { email = data; }),
      $localForage.getItem('supportForm.Phone').then(function(data)     { phone = data; }),
      $localForage.getItem('supportForm.Country').then(function(data)   { country = data; })

    ]).then(function() {
      $scope.supportForm.FirstName = firstName;
      $scope.supportForm.LastName = lastName;
      $scope.supportForm.Address = address;
      $scope.supportForm.ZipCode = zipCode;
      $scope.supportForm.City = city;
      $scope.supportForm.Email = email;
      $scope.supportForm.Phone = phone;
      $scope.supportForm.Country = country;

    }).then(function() {
      $scope.$apply();
      if (consoleDebug) console.log('...loaded.');
    });
  }

  $scope.formValueChanged = function(key, value) {
    $localForage.setItem(key, value)
        .then(function() { if (consoleDebug) console.log('...saved ' + key + ' - ' + value); });
  };
```

**Comment by scotttrinh** [comment]
I typically use `angular-localForage` as a service, too, so I'm familiar with this pattern. Here is some advice, but what you're doing is perfectly fine, too!

`getItem` supports getting an array of keys and returns them as an array of values, so you could replace that `Promise.all` call with:

```js
$localForage.getItem([
  'supportForm.FirstName',
  'supportForm.LastName'
  // etc
]).then(function (values) {
  $scope.supportForm.FirstName = values[0];
  $scope.supportForm.LastName = values[1];
  // etc
});
```

But, I think an even better thing to do is to simply store your `supportForm` as an object, so you have a single `getItem` call. Like:

```js
$localForage.getItem('supportForm').then(function (supportForm) {
  $scope.supportForm = supportForm;
});
```

To address the minlength and required directives, you're probably right that they are affecting your value. I believe those directives are intercepting the `ngModelController` and keeping the `modelValue` from changing, so even though the input is cleared, a cleared field is not a valid model value and thus it is keeping the `ng-model` -> `localforage` mapping from clearing out the field entirely.

Separate piece of advice, and feel free to ignore me since you didn't ask for my thoughts on how you're using Promises, but looking at your `Promise.all` call, I always feel it's cleaner for `.then` callbacks to use the return value of the `Promise` rather than having some higher scoped `var` that you're assigning to.  Like:

```js
Promise.all([
  $localForage.getItem('supportForm.FirstName'),
  $localForage.getItem('supportForm.LastName')
]).then(function (formValues) {
  $scope.supportForm.FirstName = formValues[0];
  $scope.supportForm.LastName = formValues[1];
});
```

If you can use ES6 destructuring, it's even prettier, like:

```js
Promise.all([
  $localForage.getItem('supportForm.FirstName'),
  $localForage.getItem('supportForm.LastName')
]).then(function ([FirstName, LastName]) {
  $scope.supportForm.FirstName = FirstName;
  $scope.supportForm.LastName = LastName;
});
```

**Comment by Diego251** [comment]
Excellent, will try that! Again thanks a lot for your help, it is very appreciated!

**Comment by scotttrinh** [comment]
One other quick thing:

If you pass `true` as the second argument to `getItem`, it will reject the promise if the value is `null` (which is what localForage will return if it doesn't find anything). You can use that to set up any default form values:

```js
$localForage
  .getItem('supportForm', true)
  .then(function (supportForm) {
    $scope.supportForm = supportForm;
  })
  .catch(function () {
    $scope.supportForm = {
      iNeedADefault: 'someDefaultValue'
    };
  });
```
