### ISSUE TITLE
How to set array Item and get array Item ?

### ISSUE THREAD

**Issue by altaihero** [ocombe/angular-localForage#48]
I read docs but i can't set array. how to set array ?

Can you make more easy array example ?

my array is $scope.test_arr = [{title: "test1", desc:"desc1"},{title: "test2", desc:"desc2"}]

Thank you

**Comment by ocombe** [comment]
If you want to set/get a whole array, just do:
`$localForage.setItem('myArrayKey', $scope.test_arr)`
`$localForage.getItem('myArrayKey').then(function(data) { ... })`

If you want to set each item of the array separately, you need to supply an array of keys instead of just a string:

`$localForage.setItem(['key1', 'key2', ....], $scope.test_arr)`
`$localForage.getItem(['key1', 'key2', ....]).then(function(data) { ... })`

**Comment by altaihero** [comment]
Thank you soo much @ocombe

**Comment by ocombe** [comment]
Anytime :)
