### ISSUE TITLE
Setting a prefix doesn't work

### ISSUE THREAD

**Issue by Chochek** [ocombe/angular-localForage#56]
```javascript
$localForageProvider.config({
  name: 'ab' // name of the database and prefix for your data
});
```

But calling `$localForage.prefix()` returns an empty string and 'ab' is not applied when setting items.

**Comment by ocombe** [comment]
The method `$localForage.prefix()` exists only for compatibility with angular-localforage < 1.0, it doesn't return the name of your database (and prefix of your data).
If you use localstorage you will see the prefix in the keys when you look at your data in the dev tools, otherwise if you use indexedDB it will be the name of the database.

**Comment by Chochek** [comment]
Ok, thanks. Closing this
