### ISSUE TITLE
Cannot add to ionic manually.

### ISSUE THREAD

**Issue by ioudas210** [ocombe/angular-localForage#61]
I have tried to add this to ionic manually using the methods defined here.

I get an error message saying that localforagemodule is not defined. Or I get a message $localForage is not defined.

Documentation is inconsistent. Says $localforage and $localForage.

**Comment by iwakari** [comment]
Hi, kudos to Olivier, angular-localForage is a very nice contribution to the angular community!

You might re-check the load order you used for localforage.js and angular-localForage.js (see the usage notes). Mozilla localforage.js must be loaded first:
<script src="path/to/localforage.js"></script>
<script src="path/to/angular-localForage.js"></script>

If interested, this is because angular-localForage utilizes a clever immediately executing function (IEF) creation method (so it can handle AMD, browsers etc; see src. lines #1-12). But, that assumes Mozilla localforage has already been attached to the Window (by being loaded before angular-localForage) object. If it has not, then you will get an 'undefined' error (see src. lines #46-53) for localforage.

I wish I had the time, here are two suggestions for someone to take on a refactoring task(s):
1) Adding a try/catch or some other check to make sure Mozilla localforage is loaded; followed by a debug log message if not
2) A rewrite of the immediately executing function as an angularjs factory. That helps solve any load order issues, and could provide a robust migration path towards angularjs 2.0 (and beyond).

Hope this helps other ionic (another beautiful bit of code) users, like myself, working with angular-localForage.

**Comment by ocombe** [comment]
@ioudas210 I checked the doc, it's `$localForage` everywhere.
Thanks @iwakari for the message :)
