### ISSUE TITLE
Question about bind and client-side models

### ISSUE THREAD

**Issue by davidtlee** [ocombe/angular-localForage#62]
I have a couple related questions: 

1) If I bind the same LocalForage value to $scope variables in different parts of my app (e.g. two different directives), will a change to the LocalForage value automatically update the $scope values for both directives?

2) I'm thinking of using angular-localForage to create a common client-side model of my app that my different views can then access in order to keep elements synchronized which are accessed in multiple places. Is that a reasonable approach? Is there a place to read best practices for this?

3) Building on question 2 (best practices): What are best practices for storing model data in angular-localForage which has associations? e.g. if I have a bunch of rooms, each of which have a bunch of users, then I need to store all the users per room. Should I only store user id's per each room key? The downside to doing this is that I'd need to make a ton of calls binding to localForage. However, if I store full users per each room key, then it's going to be a big headache trying to keep them all in sync.

Thanks!

**Comment by ocombe** [comment]
1/ no, the link is the scope, if you bind different values to the same scope they will sync, but the opposite isn't true

2/ if you need to communicate between different views, you should use events or rootScope. Storing values with localforage is made to keep data available for a later use (when the user comes back). You could use localforage to keep your different views in sync but storing data will always be slower than memory, so this shouldn't be the only reason to use it.

3/ You should think about this like you would think about a no sql database: if you need multiple data sources to make your calculations, store them together, if not store them separately (unless performance is your priority, in which case you should store them together anyway because reading/writing the data is what costs more)

**Comment by davidtlee** [comment]
Thanks! What do you mean by "if you bind different values to the same scope they will sync"? How can you bind two values to the same scope?

**Comment by ocombe** [comment]
Well if you use the same scope "name", they will sync in the sense that one value will overwrite the other

**Comment by davidtlee** [comment]
ahhhh, got it.

So just to confirm that I'm getting this right: If I do `$localForage.bind($scope, 'myStorageKey');`, that's equivalent to a `getItem` on `'myStorageKey'`, and then assigning $scope.myStorageKey to the returned value. Moreover, it's only the value that is stored, and not a pointer to the object (which means it's not updated when the object is updated). Is that correct?

**Comment by ocombe** [comment]
The first part is correct, but then it's doing a $watch on the scope so that the value from the scope keeps the database updated when the scope changes. But yes, if you change the value in the database there is no way to know that you did that and it will not update the scope

**Comment by davidtlee** [comment]
Got it, thanks so much! Makes sense now :)
