### ISSUE TITLE
Problem with localforage.INDEXEDDB driver?

### ISSUE THREAD

**Issue by xlozinguez** [ocombe/angular-localForage#63]
Is there a reason why using:
```
$localForageProvider.config({
            driver      : localforage.INDEXEDDB, // if you want to force a driver
            name        : 'myDb', 
```
would cause the error `No available storage method found.`

If I don't specify anything, it automatically falls back to WebSQL... I'm using the latest Chrome Version 42.0.2311.135  and according to http://caniuse.com/#search=indexeddb it should work :/

Help! :)

**Comment by ocombe** [comment]
Hmm no, it shouldn't do that, but the error comes from localforage itself, so you should probably open an issue there https://github.com/mozilla/localForage/issues

**Comment by xlozinguez** [comment]
Thanks @ocombe, I will do just that, it's very odd and I've been searching everywhere without finding an answer...

**Comment by xlozinguez** [comment]
@ocombe check out https://github.com/mozilla/localForage/issues/377, when running with the Chrome developer tool open, I get that error message, if I don't then it doesn't complain... that's nuts...

**Comment by xlozinguez** [comment]
I made a screencast to show you: http://screencast.com/t/NYtCFs9d3T

**Comment by williamle8300** [comment]
The problem is actually quite sneaky.

TLDR; Apple's UIWebView doesn't support indexedDB.

What's happening is that Chrome spoofs the iOS user-agent when you emulate an iPhone. Well, this spoofing is actually really effective because `localForage` will now emit an error if you configure it to exclusively use indexedDB.

If you want to have a moment of profound ennui and see indexedDB in action... just turn off Chrome dev tool's emulation so that you're actually using Chrome's own user-agent. It should work then.

You can read more info here: https://github.com/mozilla/localForage/issues/254. TLDR;x2 indexedDB for iOS is not ready.

**Comment by nayanishdamania** [comment]
i am facing issue when trying to set value using localforage into INDEXEDDB "DOMxception"
I am using chrome version 58 and also tried in chrome version 57
working fine in Mozilla Firefox.
please revert back on this issue as soon as possible 
thanks in advance.

**Comment by scotttrinh** [comment]
@nayanishdamania That looks like a separate issue from this one. Do you mind opening another issue and including more details? What kind of value are you trying to serialize? Are you using the device emulator in the Chrome Dev Tools that sets your user agent to something other than Chrome?
