### ISSUE TITLE
Get multiple Items issue

### ISSUE THREAD

**Issue by EnzoHeroguel** [ocombe/angular-localForage#66]
Hi, I got an issue with the getItem method.

I'm using the right syntax : 
$localForage.getItem(wkkeys).then(function(w) {..});

With wkkeys being an array of keys, but the function is never executed.
Any clue for this issue? I really don't understand what is going on.

Thanks

**Comment by ocombe** [comment]
Have you tried adding an error callback to see if there's something here maybe ?
```js
 $localForage.getItem(wkkeys).then(function(w) {..}, function(err) {
  console.log(err);
});
```

**Comment by EnzoHeroguel** [comment]
![capture](https://cloud.githubusercontent.com/assets/10420712/7909278/54714d30-084b-11e5-833a-377feb875486.PNG)

**Comment by ocombe** [comment]
Hmm looks like the error is within localforage itself, you might have more chance by opening an issue [there](https://github.com/mozilla/localForage/issues), but I think that you're probably storing something that causes trouble (non utf8 characters ?).
Maybe try to use localforage unminified to see where exactly the problem is in their source code.

**Comment by EnzoHeroguel** [comment]
Ok I'm gonna check this, thank you very much for your help

**Comment by ocombe** [comment]
No problem, if in the end the problem is really in angular localforage, don't hesitate to reopen the issue :)
