### ISSUE TITLE
$localForage should not start with a "$"

### ISSUE THREAD

**Issue by Toub** [ocombe/angular-localForage#86]
This service should not start with a "$" prefix, reserved for angular own services.
Of course, renaming the service means releasing a new major version due to breaking compatibilities.

> The $ prefix is there to namespace Angular-provided services. To prevent collisions it's best to avoid naming your services and models anything that begins with a $.
https://docs.angularjs.org/tutorial/step_05

> Do not use $ prefix for the names of variables, properties and methods. This prefix is reserved for AngularJS usage.
https://github.com/mgechev/angularjs-style-guide#others

**Comment by scotttrinh** [comment]
While I agree with this sentiment, I feel like this is too much of a breaking change to really go with. I feel like the spirit of the advice is to not name services/etc. in your own app as `$service` to avoid collision with library code that uses that convention, so I feel 3rd party libraries are a bit of an exception. Going forward, I think it's good style to pick a vendor-specific prefix instead of `$`, but it would cause *everyone* to have to change their code, which I feel is just a little too heavy-handed.

I'll consider revisiting this if the angular core team ever thinks about making an official module for `localForage`. :wink:
