### ISSUE TITLE
Binding should be bidirectional

### ISSUE THREAD

**Issue by Takkuz** [ocombe/angular-localForage#97]
As #62 points out when I bind a key on DB I suppose that an update from DB should update the view itself. Without the needs to create a listener on the "change" event which filters out that key. The event should be managed inside the bind function.

**Comment by scotttrinh** [comment]
I see where you're coming from since you imagine localForage to be something similar to a normal service object, but I would think of it more like a backend. When something changes in your remote database, you still have to fetch it even if you've bound the results of the initial fetch to a scope property. I think what this and #62 is pointing to is maybe a simpler way to get updates from localForage, no? We might be able to explore a better API than watchers on events, but I don't think we'll land on automatically watching for changes and pushing to the scope for you, since I think that breaks with the nature of the in-browser database.

Not sure if this is your use case, but you might create a regular service/factory to store your data, and make periodic saves to localForage for session-to-session persistence instead of trying to get localForage to be more like an in-memory object.

For now, I think this is a closed issue, but I'll leave it open to hear any additional input you might have!

**Comment by Takkuz** [comment]
Thank you for your answer. You were really comprehensive in your own reasons. I've done what you said in fact. ;) Good work anyway...

**Comment by scotttrinh** [comment]
Glad you were able to get it figured out. 👍
